version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      major-updates:
        update-types:
          - "major"
        patterns:
          - "@stellar/freighter-api"
          - "@stellar/stellar-sdk"
          - "next"
          - "react"
          - "react-dom"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      major-updates:
        update-types:
          - "major"
